System construction and test

In [ ]:
from datetime import date, datetime
import pandas as pd
import yfinance as yf
import time
#from Alert import Alert
pd.options.mode.chained_assignment = None  # default='warn'
#alert = Alert('1h','GGAL')

input:
    
     Titulo  : example: GGAL
     frequencia de tick : 1h (frequencia mais alta)
     dftitulo : vista do BD sqtitulosalpha.bd (testar ultimos periodas)
Parametros a variar para back testing ( definir rangos de variação)
     k, d, smooth (parametros do stch)
     dayM  (frequencia media) (multiplicador da frequencia mais alta) exemplo: 5
     semM  (frequencia baixa) (multiplicador da frequencia media) exemplo: 7

In [ ]:
dataini = '2013-04-03 19:30:00'
datafim = '2023-04-03 19:30:00'

In [ ]:
%%timeit
import sqlite3
import pandas as pd

# Caminho para o banco de dados
caminho_bd = r'C:\Users\scitr\anaconda_projects\Trading_System\Dados_Fontes\Alpha_Vantage\sqtitulosalpha.db'

# Conectando ao banco
conexao = sqlite3.connect(caminho_bd)

# Lendo a view
#consulta = 'SELECT * FROM vwtitulosdados ORDER BY datetime'
consulta = f"""
SELECT * FROM vwtitulosdados
WHERE datetime BETWEEN '{dataini}' AND '{datafim}'
ORDER BY datetime
"""

dftitulosdados = pd.read_sql_query(consulta, conexao)

# Fechando a conexão
conexao.close()

# Exibindo os primeiros registros para conferir
#display(dftitulosdados)
dftitulosdados = dftitulosdados.drop(columns=["symbol", "moeda", "intervalo","volume"])
#display(len(dftitulosdados))
#display(dftitulosdados.head(10))

In [ ]:

i = 'high'
K = 16  
D = 5    
smoth = 5  
dayM = 8  
semM = 4
stpl = 0.02

In [ ]:
#%%timeit
# Stochastic calculation
def stochastic(df, i, K, D, smoth):
        
    df["k"] = (100. * (df.close - df.low.rolling(K).min()) /
        (df.high.rolling(K).max() - df.low.rolling(K).min()))
    
    df["k" + i] = df.k.rolling(smoth).mean()
    df["d" + i] = df["k" + i].rolling(D).mean()
    
    df.drop(columns=["k"], inplace=True)  

    return df
dfstoch = stochastic(dftitulosdados, i, K, D, smoth)

#display (dfstoch.head(100))
#%time dfstoch

In [ ]:
#%%timeit
def set_test( df, intervalo, k, d, smth, dayM, semM):  
       

        df = stochastic(df, "high", k, d, smth)
        df = stochastic(df, "med", k*dayM, d*dayM, smth*dayM)
        df = stochastic(df, "low", k*dayM*semM, d*dayM*semM, smth*dayM*semM)
    
        return df

dfstoch_hml= set_test(dfstoch, i , K, D, smoth, dayM , semM )
#%time set_test(dfstoch, i , K, D, smoth, dayM , semM ) 
#display (dfstoch_hml.head(10))

In [ ]:
#%%timeit
#pd.set_option('display.max_rows', None)
df = dfstoch_hml
df["longbuylow"] = ((df["klow"] > 20) & (df["klow"] > df["dlow"])).astype(int)
df["longbuymed"] = ((df["kmed"] > 20) & (df["kmed"] > df["dmed"])).astype(int)
df["longbuyhigh"] = ((df["khigh"] > 20) & (df["khigh"] > df["dhigh"])).astype(int)

In [ ]:
#%%timeit
def long_buy_crits( df):   
   
    
    df["state"] = "standby"    
    
    
    for i in range(1, len(df)):        

        # long buy  states          

        if  df.loc[i, "longbuyhigh"] == 1 and df.loc[i, "longbuymed"] == 1 and df.loc[i, "longbuylow"] == 1 and df.loc[i-1, "state"] == "standby" :        
            df.loc[i, "state"] = "buylong"

            
            
        if  df.loc[i, "longbuymed"] == 1 and df.loc[i, "longbuylow"] == 1 and (df.loc[i-1, "state"] == "buylong" or df.loc[i-1, "state"] == "staylong") :
            df.loc[i, "state"] = "staylong" 

            
        if  df.loc[i, "longbuyhigh"] == 1 and df.loc[i, "longbuylow"] == 1 and df.loc[i, "longbuymed"] == 0 and (df.loc[i-1, "state"] == "buylong" or df.loc[i-1, "state"] == "staylong") :
            df.loc[i, "state"] = "staylong"

        # long sell state and price 
        
        if  (df.loc[i, "longbuylow"] == 0 ) and  (df.loc[i-1, "state"] == "buylong" or df.loc[i-1, "state"] == "staylong")  :
             df.loc[i, "state"] = "selllong"
            
            
        if  df.loc[i, "longbuyhigh"] == 0 and df.loc[i, "longbuymed"] == 0 and  (df.loc[i-1, "state"] == "buylong" or df.loc[i-1, "state"] == "staylong") :
             df.loc[i, "state"] = "selllong"
             
            
        if  (df.loc[i, "longbuylow"] == 0 or df.loc[i, "longbuymed"] == 0) and  df.loc[i-1, "state"] == "selllong"  :
             df.loc[i, "state"] = "standby" 
      
    return df
    
dfstate = long_buy_crits(dfstoch_hml) 

#%time long_buy_crits(dfstoch_hml)   
#display (df)

In [ ]:
dfstate = long_buy_crits(dfstoch_hml)
pd.set_option('display.max_rows', None)
dfbuysell = dfstate[(dfstate['state'] == 'buylong') | (dfstate['state'] == 'selllong')]
#df_intervalo = dfstate.iloc[800:1500] 
#display(df_intervalo)
display (len(dfbuysell))
display(dfbuysell)

In [ ]:
#%%timeit
import numpy as np

def long_buy_crits_numpy(df):
    n = len(df)
    state_array = np.full(n, "standby", dtype=object)  # inicializa com "standby"
    estado_anterior = "standby"

    high = df["longbuyhigh"].to_numpy()
    med = df["longbuymed"].to_numpy()
    low = df["longbuylow"].to_numpy()

    for i in range(1, n):
        if high[i] == 1 and med[i] == 1 and low[i] == 1 and estado_anterior == "standby":
            state_array[i] = "buylong"
            estado_anterior = "buylong"
        elif med[i] == 1 and low[i] == 1 and estado_anterior in ["buylong", "staylong"]:
            state_array[i] = "staylong"
            estado_anterior = "staylong"
        elif high[i] == 1 and low[i] == 1 and med[i] == 0 and estado_anterior in ["buylong", "staylong"]:
            state_array[i] = "staylong"
            estado_anterior = "staylong"
        elif low[i] == 0 and estado_anterior in ["buylong", "staylong"]:
            state_array[i] = "selllong"
            estado_anterior = "selllong"
        elif high[i] == 0 and med[i] == 0 and estado_anterior in ["buylong", "staylong"]:
            state_array[i] = "selllong"
            estado_anterior = "selllong"
        elif (low[i] == 0 or med[i] == 0) and estado_anterior == "selllong":
            state_array[i] = "standby"
            estado_anterior = "standby"
        else:
            state_array[i] = estado_anterior

    df["state"] = state_array
    return df

In [ ]:
dfstate = long_buy_crits_numpy(dfstoch_hml)
pd.set_option('display.max_rows', None)
dfbuysellop = dfstate[(dfstate['state'] == 'buylong') | (dfstate['state'] == 'selllong')]
#df_intervalo = dfstate.iloc[800:1500] 
#display(df_intervalo)
display (len(dfbuysell))
display(dfbuysell)

In [ ]:
#%%timeit
def Stop_Loss_Reentry (dfstate, stpl) :

    df = dfstate[(dfstate['state'] == 'buylong') | (dfstate['state'] == 'staylong')]
    df = df.reset_index(drop=True)
    df = df.drop(columns=["open" ,	"high" , "low" , "khigh","dhigh","kmed" ,"dmed","klow","dlow"])
    #drop(columns=["symbol", "moeda", "intervalo","volume"])
    df["stpl"] = 0.0
    stoplossprice = 0.0
    lastlongbuyprice = 0.0

    for i in range(0, len(df)):
        
        if df.loc[i, "state"] == "buylong" :
           stoplossprice = df.loc[i, "close"]
           df.loc[i,"stpl"] = df.loc[i, "close"] - stoplossprice * (1 - stpl)
           
        if df.loc[i, "state"]== "staylong" :
           df.loc[i, "stpl"] = df.loc[i, "close"] - stoplossprice * (1- stpl)
            
           if df.loc[i, "stpl"] < 0.0 :
                df.loc[i, "state"] = "selllong"
               
           if df.loc[i, "stpl"] > 0.0 and   (df.loc[i-1, "state"] == "selllong" or df.loc[i-1, "state"] == "sellstay") :
                df.loc[i, "state"] = "buylong"
               
           if df.loc[i, "stpl"] < 0.0 and   (df.loc[i-1, "state"] == "selllong" or df.loc[i-1, "state"] == "sellstay") :
                df.loc[i, "state"] = "sellstay"

    return df

In [ ]:
pd.set_option('display.max_rows', None)
dflongstpl = Stop_Loss_Reentry (dfstate, stpl)
display(len(dflongstpl))
df_intervalo = dflongstpl.iloc[0:300] 
display(df_intervalo)

In [ ]:
dflongsell = dfstate.drop(columns=["open" ,	"high" , "low" , "khigh","dhigh","kmed" ,"dmed","klow","dlow"])
dflongsell = dflongsell[(dflongsell['state'] == 'selllong')]
display (dflongsell)

dfbuysellstpl = dflongstpl[(dflongstpl['state'] == 'buylong') | (dflongstpl['state'] == 'selllong')]
df_intervalo = dfbuysellstpl.iloc[0:100]
#display(len(dfbuysell))
#display(df_intervalo)

In [ ]:
#%%timeit
# Suponha que df1 e df2 têm as mesmas colunas (incluindo 'datetime')
dflongbuysell = pd.concat([dflongsell, dfbuysellstpl], ignore_index=True)

# Ordenar pelo datetime (certifique-se de que é do tipo datetime)
dflongbuysell["datetime"] = pd.to_datetime(dflongbuysell["datetime"])
dflongbuysell = dflongbuysell.sort_values("datetime").reset_index(drop=True)
display (dflongbuysell)

In [271]:
#%%timeit
df = dflongbuysell

# Supondo que seu DataFrame se chame df
cond = (df["state"] == "selllong") & (df["stpl"].isna()) & (df["state"].shift(1) == "selllong")

dflongbuysell = df[~cond].reset_index(drop=True)
display (dflongbuysell.head(10))

,datetime,close,longbuylow,longbuymed,longbuyhigh,state,stpl
0,2013-09-06 12:00:00,5.6531,1,1,1,buylong,0.113062
1,2013-09-17 10:00:00,6.6434,1,0,0,selllong,NaN
2,2013-09-18 16:00:00,6.8149,1,1,1,buylong,0.136298
3,2013-09-30 10:00:00,7.2906,1,0,0,selllong,NaN
4,2013-10-10 11:00:00,7.9534,1,1,1,buylong,0.159068
5,2013-10-17 13:00:00,8.1561,1,0,0,selllong,NaN
6,2014-02-28 14:00:00,7.7272,1,1,1,buylong,0.154544
7,2014-03-10 16:00:00,7.9846,1,0,0,selllong,NaN
8,2014-03-20 11:00:00,8.4992,1,1,1,buylong,0.169984
9,2014-04-01 10:00:00,9.5596,1,0,0,selllong,NaN

Métricas

In [281]:
df = dflongbuysell
df ["index"] = 100.
for i in range(1, len(df)):       

                 

    if  df.loc[i, "state"] == "selllong" :
            df.loc[i, "index"] = ((df.loc[i,"close"]-df.loc[i-1,"close"])/df.loc[i-1,"close"]+1) * df.loc[i-1, "index"]
        
    if  df.loc[i, "state"] == "buylong" :
            df.loc[i, "index"] =  df.loc[i-1, "index"]


display (df)

,datetime,close,longbuylow,longbuymed,longbuyhigh,state,stpl,index
0,2013-09-06 12:00:00,5.6531,1,1,1,buylong,0.113062,100.000000
1,2013-09-17 10:00:00,6.6434,1,0,0,selllong,NaN,117.517822
2,2013-09-18 16:00:00,6.8149,1,1,1,buylong,0.136298,117.517822
3,2013-09-30 10:00:00,7.2906,1,0,0,selllong,NaN,125.720911
4,2013-10-10 11:00:00,7.9534,1,1,1,buylong,0.159068,125.720911
5,2013-10-17 13:00:00,8.1561,1,0,0,selllong,NaN,128.925028
6,2014-02-28 14:00:00,7.7272,1,1,1,buylong,0.154544,128.925028
7,2014-03-10 16:00:00,7.9846,1,0,0,selllong,NaN,133.219637
8,2014-03-20 11:00:00,8.4992,1,1,1,buylong,0.169984,133.219637
9,2014-04-01 10:00:00,9.5596,1,0,0,selllong,NaN,149.840743
10,2014-04-02 12:00:00,10.4407,1,1,1,buylong,0.208814,149.840743
11,2014-04-03 13:00:00,10.1912,1,1,0,selllong,-0.040686,146.260019
12,2014-04-03 14:00:00,10.2419,1,1,0,buylong,0.010014,146.260019
13,2014-04-04 12:00:00,10.1444,1,1,0,selllong,-0.087486,144.867665
14,2014-04-23 12:00:00,10.8345,1,1,1,buylong,0.216690,144.867665
15,2014-04-25 09:00:00,10.5577,1,1,0,selllong,-0.060110,141.166583
16,2014-04-28 09:00:00,10.6201,1,1,1,buylong,0.002290,141.166583
17,2014-04-28 10:00:00,10.4953,1,1,1,selllong,-0.122510,139.507692
18,2014-06-25 11:00:00,11.6902,1,1,1,buylong,0.233804,139.507692
19,2014-06-26 14:00:00,11.3627,1,1,0,selllong,-0.093696,135.599395
20,2014-06-30 18:00:00,11.6746,1,1,1,buylong,0.218204,135.599395
21,2014-07-08 11:00:00,11.9710,0,1,1,selllong,NaN,139.042054
22,2014-07-10 13:00:00,13.2109,1,1,1,buylong,0.264218,139.042054
23,2014-07-14 13:00:00,12.9458,1,1,0,selllong,-0.000882,136.251930
24,2014-07-14 14:00:00,13.0550,1,1,0,buylong,0.108318,136.251930
25,2014-07-15 09:00:00,12.8288,1,1,0,selllong,-0.117882,133.891134
26,2014-10-30 12:00:00,10.9571,1,1,1,buylong,0.219142,133.891134
27,2014-11-05 10:00:00,11.6122,1,0,0,selllong,NaN,141.896180
28,2014-11-05 15:00:00,11.9164,1,1,1,buylong,0.238328,141.896180
29,2014-11-06 10:00:00,11.7292,1,0,0,selllong,NaN,139.667070
30,2014-11-26 15:00:00,12.6182,1,1,1,buylong,0.252364,139.667070
31,2014-12-01 10:00:00,12.0489,1,1,0,selllong,-0.316936,133.365659
32,2014-12-05 13:00:00,12.9380,1,1,1,buylong,0.258760,133.365659
33,2014-12-08 12:00:00,12.6494,1,1,0,selllong,-0.029840,130.390753
34,2014-12-08 16:00:00,12.7207,1,1,0,buylong,0.041460,130.390753
35,2014-12-09 09:00:00,12.2361,1,1,0,selllong,-0.443140,125.423467
36,2015-01-14 15:00:00,12.7898,1,1,1,buylong,0.255796,125.423467
37,2015-01-23 11:00:00,12.6026,1,0,0,selllong,NaN,123.587686
38,2015-02-05 10:00:00,13.3630,1,1,1,buylong,0.267260,123.587686
39,2015-02-18 14:00:00,15.1762,1,0,0,selllong,NaN,140.357063
40,2015-02-25 10:00:00,17.1805,1,1,1,buylong,0.343610,140.357063
41,2015-02-25 14:00:00,16.5176,1,1,0,selllong,-0.319290,134.941464
42,2015-02-25 16:00:00,16.9832,1,1,0,buylong,0.146310,134.941464
43,2015-02-26 09:00:00,16.4006,1,1,0,selllong,-0.436290,130.312366
44,2015-03-06 12:00:00,17.3832,1,1,1,buylong,0.347664,130.312366
45,2015-03-20 13:00:00,20.2453,1,0,0,selllong,NaN,151.767969
46,2015-07-15 09:00:00,16.3098,1,1,1,buylong,0.326196,151.767969
47,2015-07-20 10:00:00,15.8492,1,1,0,selllong,-0.134404,147.481937
48,2015-07-20 11:00:00,16.1458,1,1,0,buylong,0.162196,147.481937
49,2015-07-20 12:00:00,15.9038,1,1,0,selllong,-0.079804,145.271416
50,2015-08-04 11:00:00,14.8420,1,1,1,buylong,0.296840,145.271416
51,2015-08-18 10:00:00,15.8804,1,0,0,selllong,NaN,155.435129
52,2015-08-27 15:00:00,15.3963,1,1,1,buylong,0.307926,155.435129
53,2015-08-31 09:00:00,14.9123,1,1,0,selllong,-0.176074,150.548851
54,2015-08-31 12:00:00,15.1387,1,1,0,buylong,0.050326,150.548851
55,2015-08-31 14:00:00,14.9982,1,1,0,selllong,-0.090174,149.151630
56,2015-09-04 14:00:00,15.1153,1,1,1,buylong,0.026926,149.151630
57,2015-09-04 15:00:00,15.0760,1,1,1,selllong,-0.012374,148.763834
58,2015-09-08 09:00:00,15.3963,1,1,1,buylong,0.307926,148.763834
59,2015-09-17 13:00:00,15.4119,1,0,0,selllong,NaN,148.914566
60,2015-10-20 12:00:00,16.2278,1,1,1,buylong,0.324556,148.914566
61,2015-10-26 11:00:00,18.8160,1,0,0,selllong,NaN,172.665208
62,2015-11-03 14:00:00,19.8700,1,1,1,buylong,0.397400,172.665208
63,2015-11-05 13:00:00,19.9637,1,0,0,selllong,NaN,173.479437
64,2015-11-12 11:00:00,20.5883,1,1,1,buylong,0.411766,173.479437
65,2015-11-23 14:00:00,20.2292,1,0,0,selllong,NaN,170.453618
66,2016-02-22 11:00:00,22.5246,1,1,1,buylong,0.450492,170.453618
67,2016-02-23 12:00:00,22.0717,1,1,0,selllong,-0.002408,167.026324
68,2016-02-23 13:00:00,22.1342,1,1,0,buylong,0.060092,167.026324
69,2016-02-24 09:00:00,21.8219,1,1,1,selllong,-0.252208,164.669685
70,2016-02-24 11:00:00,22.3372,1,0,1,buylong,0.263092,164.669685
71,2016-02-25 12:00:00,23.2819,1,0,0,selllong,NaN,171.634006
72,2016-03-18 10:00:00,22.8056,1,1,1,buylong,0.456112,171.634006
73,2016-03-23 16:00:00,22.5011,0,1,0,selllong,NaN,169.342352
74,2016-06-13 14:00:00,23.3207,1,1,1,buylong,0.466414,169.342352
75,2016-06-21 12:00:00,24.3604,1,0,0,selllong,NaN,176.892093
76,2016-07-05 14:00:00,24.1259,1,1,1,buylong,0.482518,176.892093
77,2016-07-20 13:00:00,24.7357,1,0,0,selllong,NaN,181.363172
78,2016-10-07 11:00:00,24.7513,1,1,1,buylong,0.495026,181.363172
79,2016-10-11 09:00:00,25.0640,1,0,0,selllong,NaN,183.654456
80,2016-11-07 15:00:00,24.0477,1,1,1,buylong,0.480954,183.654456
81,2016-11-08 16:00:00,24.1493,0,1,1,selllong,NaN,184.430384
82,2017-01-06 10:00:00,23.1174,1,1,1,buylong,0.462348,184.430384
83,2017-01-24 14:00:00,25.9865,1,0,0,selllong,NaN,207.320035
84,2017-02-07 12:00:00,25.6660,1,1,1,buylong,0.513320,207.320035
85,2017-02-16 15:00:00,26.7683,1,0,0,selllong,NaN,216.223989
86,2017-03-23 09:00:00,29.0590,1,1,1,buylong,0.581180,216.223989
87,2017-03-28 10:00:00,29.6297,1,0,0,selllong,NaN,220.470488
88,2017-04-06 13:00:00,31.2323,1,1,1,buylong,0.624646,220.470488
89,2017-04-10 13:00:00,30.7007,1,0,0,selllong,NaN,216.717895
90,2017-05-31 13:00:00,35.1206,1,1,1,buylong,0.702412,216.717895
91,2017-06-07 11:00:00,35.6896,1,0,0,selllong,NaN,220.229011
92,2017-08-22 12:00:00,33.3062,1,1,1,buylong,0.666124,220.229011
93,2017-08-30 14:00:00,35.2303,1,0,0,selllong,NaN,232.951646
94,2017-09-01 16:00:00,36.0689,1,1,1,buylong,0.721378,232.951646
95,2017-09-08 13:00:00,36.5079,1,0,0,selllong,NaN,235.786936
96,2017-09-21 15:00:00,37.5738,1,1,1,buylong,0.751476,235.786936
97,2017-10-11 12:00:00,41.3636,1,0,0,selllong,NaN,259.569075
98,2017-10-17 14:00:00,42.8175,1,1,1,buylong,0.856350,259.569075
99,2017-10-18 14:00:00,41.8770,1,1,0,selllong,-0.084150,253.867557
100,2017-10-18 15:00:00,42.0612,1,1,0,buylong,0.100050,253.867557
101,2017-10-19 09:00:00,41.8065,1,1,0,selllong,-0.154650,252.330272
102,2017-10-19 10:00:00,42.0102,1,1,0,buylong,0.049050,252.330272
103,2017-10-20 09:00:00,42.0651,1,0,0,selllong,NaN,252.660024
104,2017-12-06 13:00:00,46.6423,1,1,1,buylong,0.932846,252.660024
105,2017-12-13 15:00:00,50.9374,1,0,0,selllong,NaN,275.926459
106,2018-01-02 13:00:00,52.6931,1,1,1,buylong,1.053862,275.926459
107,2018-01-08 12:00:00,52.5753,1,0,0,selllong,NaN,275.309602
108,2018-01-18 12:00:00,57.0195,1,1,1,buylong,1.140390,275.309602
109,2018-01-22 10:00:00,55.3736,1,1,0,selllong,-0.505510,267.362635
110,2018-04-10 12:00:00,52.5755,1,1,1,buylong,1.051510,267.362635
111,2018-04-13 11:00:00,51.3998,1,1,0,selllong,-0.124190,261.383838
112,2018-04-13 13:00:00,51.5252,1,1,0,buylong,0.001210,261.383838
113,2018-04-13 14:00:00,51.3842,1,1,0,selllong,-0.139790,260.668554
114,2018-09-25 14:00:00,22.8111,1,1,1,buylong,0.456222,260.668554
115,2018-09-26 19:00:00,21.5399,1,1,0,selllong,-0.814978,246.142211
116,2018-09-27 07:00:00,23.0953,1,1,0,buylong,0.740422,246.142211
117,2018-09-27 10:00:00,22.4873,1,0,0,selllong,NaN,239.662344
118,2018-10-16 17:00:00,19.5580,1,1,1,buylong,0.391160,239.662344
119,2018-10-17 09:00:00,18.1841,1,1,1,selllong,-0.982740,222.826671
120,2018-11-07 15:00:00,20.8371,1,1,1,buylong,0.416742,222.826671
121,2018-11-09 09:00:00,20.2528,1,1,0,selllong,-0.167558,216.578315
122,2018-11-19 16:00:00,20.8766,1,1,1,buylong,0.417532,216.578315
123,2018-11-20 09:00:00,20.0554,1,1,1,selllong,-0.403668,208.059011
124,2018-11-21 10:00:00,20.6318,1,1,1,buylong,0.172732,208.059011
125,2018-11-21 13:00:00,20.3555,1,1,1,selllong,-0.103568,205.272695
126,2018-11-21 15:00:00,20.5607,1,1,1,buylong,0.101632,205.272695
127,2018-11-26 14:00:00,19.9054,1,1,0,selllong,-0.553668,198.730350
128,2018-11-27 09:00:00,20.4921,1,1,0,buylong,0.033032,198.730350
129,2018-11-27 12:00:00,20.1817,1,0,1,selllong,-0.277368,195.720121
130,2018-11-30 14:00:00,21.8999,1,1,1,buylong,0.437998,195.720121
131,2018-12-06 07:00:00,21.3187,1,1,0,selllong,-0.143202,190.525918
132,2018-12-06 12:00:00,21.5161,1,1,1,buylong,0.054198,190.525918
133,2018-12-07 13:00:00,21.9188,1,0,0,selllong,NaN,194.091843
134,2018-12-31 15:00:00,21.7451,1,1,1,buylong,0.434902,194.091843
135,2019-01-11 16:00:00,25.6536,1,0,0,selllong,NaN,228.978229
136,2019-01-23 13:00:00,26.6879,1,1,1,buylong,0.533758,228.978229
137,2019-01-30 10:00:00,27.3985,1,0,0,selllong,NaN,235.075072
138,2019-02-05 10:00:00,29.6962,1,1,1,buylong,0.593924,235.075072
139,2019-02-06 13:00:00,28.9145,1,1,0,selllong,-0.187776,228.887136
140,2019-05-14 10:00:00,19.4948,1,1,1,buylong,0.389896,228.887136
141,2019-05-20 10:00:00,19.0609,1,1,0,selllong,-0.044004,223.792745
142,2019-05-20 11:00:00,19.2408,1,1,1,buylong,0.135896,223.792745
143,2019-05-30 15:00:00,20.7036,1,0,0,selllong,NaN,240.806800
144,2019-06-06 10:00:00,21.7268,1,1,1,buylong,0.434536,240.806800
145,2019-06-14 16:00:00,26.8987,1,0,0,selllong,NaN,298.129033
146,2019-06-24 16:00:00,27.4023,1,1,1,buylong,0.548046,298.129033
147,2019-06-26 13:00:00,26.5150,1,1,0,selllong,-0.339254,288.475468
148,2019-06-26 15:00:00,26.9466,1,1,0,buylong,0.092346,288.475468
149,2019-07-01 14:00:00,28.3296,1,0,0,selllong,NaN,303.281105
150,2019-07-10 08:00:00,30.4958,1,1,1,buylong,0.609916,303.281105
151,2019-07-10 11:00:00,30.0882,1,0,0,selllong,NaN,299.227518
152,2019-07-12 10:00:00,30.3919,1,1,1,buylong,0.607838,299.227518
153,2019-07-15 11:00:00,29.3847,1,0,0,selllong,NaN,289.310995
154,2019-11-07 12:00:00,10.2799,1,1,1,buylong,0.205598,289.310995
155,2019-11-07 15:00:00,10.0480,1,1,1,selllong,-0.026302,282.784549
156,2019-11-07 16:00:00,10.1120,1,1,1,buylong,0.037698,282.784549
157,2019-11-08 10:00:00,10.0720,1,1,0,selllong,-0.002302,281.665939
158,2019-11-11 09:00:00,10.2079,1,1,0,buylong,0.133598,281.665939
159,2019-11-11 12:00:00,10.0241,1,1,1,selllong,-0.050202,276.594357
160,2019-11-11 13:00:00,10.1520,1,1,1,buylong,0.077698,276.594357
161,2019-11-12 10:00:00,9.9520,1,1,0,selllong,-0.122302,271.145296
162,2019-11-21 15:00:00,10.1360,1,1,1,buylong,0.202720,271.145296
163,2019-12-03 11:00:00,9.9841,1,0,0,selllong,NaN,267.081861
164,2019-12-12 10:00:00,10.8194,1,1,1,buylong,0.216388,267.081861
165,2019-12-13 10:00:00,11.8631,1,0,0,selllong,NaN,292.846075
166,2019-12-18 13:00:00,12.3502,1,1,1,buylong,0.247004,292.846075
167,2019-12-18 14:00:00,11.9186,1,1,1,selllong,-0.184596,282.612041
168,2019-12-19 09:00:00,12.3102,1,1,0,buylong,0.207004,282.612041
169,2019-12-19 10:00:00,11.7507,1,1,0,selllong,-0.352496,269.767292
170,2019-12-23 11:00:00,13.0377,1,1,1,buylong,0.260754,269.767292
171,2019-12-31 16:00:00,12.9737,1,0,0,selllong,NaN,268.443047
172,2020-05-20 13:00:00,6.8346,1,1,1,buylong,0.136692,268.443047
173,2020-05-28 16:00:00,7.0584,1,0,0,selllong,NaN,277.233255
174,2020-06-05 07:00:00,8.5932,1,1,1,buylong,0.171864,277.233255
175,2020-06-05 09:00:00,8.3854,1,1,1,selllong,-0.035936,270.529225
176,2020-06-05 10:00:00,8.5612,1,1,1,buylong,0.139864,270.529225
177,2020-06-05 11:00:00,8.3774,1,1,0,selllong,-0.043936,264.721246
178,2020-06-08 08:00:00,8.6731,1,1,0,buylong,0.251764,264.721246
179,2020-06-09 09:00:00,8.4173,1,1,0,selllong,-0.004036,256.913692
180,2020-06-09 10:00:00,8.7691,1,1,0,buylong,0.347764,256.913692
181,2020-06-10 09:00:00,8.2734,1,1,0,selllong,-0.147936,242.390865
182,2020-06-10 11:00:00,8.5532,1,1,0,buylong,0.131864,242.390865
183,2020-06-11 08:00:00,8.3374,1,0,1,selllong,-0.083936,236.275266
184,2020-06-25 16:00:00,8.5292,1,1,1,buylong,0.170584,236.275266
185,2020-06-26 09:00:00,8.3054,1,1,1,selllong,-0.053216,230.075575
186,2020-07-16 14:00:00,9.2232,1,1,1,buylong,0.184464,230.075575
187,2020-07-16 16:00:00,9.2007,1,0,0,selllong,NaN,229.514305
188,2020-07-22 17:00:00,9.8722,1,1,1,buylong,0.197444,229.514305
189,2020-07-29 11:00:00,9.7443,1,0,0,selllong,NaN,226.540816
190,2020-11-25 16:00:00,7.1406,1,1,1,buylong,0.142812,226.540816
191,2020-11-30 15:00:00,6.9546,1,1,0,selllong,-0.043188,220.639828
192,2020-12-01 08:00:00,7.1163,1,1,0,buylong,0.118512,220.639828
193,2020-12-04 11:00:00,7.2942,1,0,0,selllong,NaN,226.155592
194,2020-12-04 15:00:00,7.3266,1,1,1,buylong,0.146532,226.155592
195,2020-12-07 16:00:00,7.1567,1,0,0,selllong,NaN,220.911162
196,2020-12-29 10:00:00,7.2214,1,1,1,buylong,0.144428,220.911162
197,2020-12-31 09:00:00,7.0435,1,1,0,selllong,-0.033472,215.468991
198,2020-12-31 10:00:00,7.1163,1,1,0,buylong,0.039328,215.468991
199,2020-12-31 15:00:00,7.0678,1,1,1,selllong,-0.009172,214.000497
200,2021-04-08 14:00:00,6.2591,1,1,1,buylong,0.125182,214.000497
201,2021-04-09 10:00:00,6.1095,1,1,0,selllong,-0.024418,208.885628
202,2021-05-12 16:00:00,6.2187,1,1,1,buylong,0.124374,208.885628
203,2021-05-24 16:00:00,6.5917,1,0,0,selllong,NaN,221.414668
204,2021-05-28 16:00:00,7.1998,1,1,1,buylong,0.143996,221.414668
205,2021-06-09 09:00:00,7.8971,1,0,0,selllong,NaN,242.858659
206,2021-06-09 13:00:00,8.3066,1,1,1,buylong,0.166132,242.858659
207,2021-06-10 14:00:00,8.3633,1,0,0,selllong,NaN,244.516387
208,2021-08-25 14:00:00,8.1565,1,1,1,buylong,0.163130,244.516387
209,2021-08-31 15:00:00,8.7403,1,0,0,selllong,NaN,262.017603
210,2021-09-13 04:00:00,9.9728,1,1,1,buylong,0.199456,262.017603
211,2021-09-13 06:00:00,9.7376,1,1,1,selllong,-0.035744,255.838141
212,2021-09-13 07:00:00,9.8106,1,1,1,buylong,0.037256,255.838141
213,2021-09-13 09:00:00,9.7701,1,1,1,selllong,-0.003244,254.781993
214,2021-10-22 15:00:00,9.2674,1,1,1,buylong,0.185348,254.781993
215,2021-10-27 09:00:00,9.4133,1,0,0,selllong,NaN,258.793117
216,2021-11-05 15:00:00,9.2349,1,1,1,buylong,0.184698,258.793117
217,2021-11-15 09:00:00,8.9998,1,1,1,selllong,-0.050402,252.204821
218,2021-11-15 10:00:00,9.1701,1,1,1,buylong,0.119898,252.204821
219,2021-11-15 13:00:00,9.2106,1,0,0,selllong,NaN,253.318690
220,2022-01-13 10:00:00,7.8890,1,1,1,buylong,0.157780,253.318690
221,2022-01-13 15:00:00,7.7025,1,1,0,selllong,-0.028720,247.330107
222,2022-02-04 14:00:00,7.5404,1,1,1,buylong,0.150808,247.330107
223,2022-02-07 16:00:00,7.5971,1,0,0,selllong,NaN,249.189904
224,2022-02-22 09:00:00,8.1890,1,1,1,buylong,0.163780,249.189904
225,2022-02-24 05:00:00,7.4998,1,1,0,selllong,-0.525420,228.217663
226,2022-02-24 14:00:00,8.0755,1,1,1,buylong,0.050280,228.217663
227,2022-02-25 16:00:00,8.1485,1,0,0,selllong,NaN,230.280679
228,2022-03-15 16:00:00,8.0512,1,1,1,buylong,0.161024,230.280679
229,2022-03-29 16:00:00,8.6674,1,0,0,selllong,NaN,247.905252
230,2022-05-27 11:00:00,8.0168,1,1,1,buylong,0.160336,247.905252
231,2022-05-31 10:00:00,7.8482,1,1,0,selllong,-0.008264,242.691597
232,2022-05-31 11:00:00,7.8735,1,1,0,buylong,0.017036,242.691597
233,2022-05-31 13:00:00,7.8398,1,1,0,selllong,-0.016664,241.652833
234,2022-08-04 08:00:00,6.8282,1,1,1,buylong,0.136564,241.652833
235,2022-08-04 10:00:00,6.6385,1,1,0,selllong,-0.053136,234.939271
236,2022-08-12 11:00:00,6.6428,1,1,1,buylong,0.132856,234.939271
237,2022-08-19 12:00:00,6.6470,1,0,0,selllong,NaN,235.087815
238,2022-08-25 16:00:00,7.3509,1,1,1,buylong,0.147018,235.087815
239,2022-08-30 14:00:00,7.1738,1,1,0,selllong,-0.030082,229.424012
240,2022-09-09 10:00:00,7.5514,1,1,1,buylong,0.151028,229.424012
241,2022-09-15 11:00:00,7.6122,1,0,0,selllong,NaN,231.271216
242,2022-12-20 09:00:00,6.9528,1,1,1,buylong,0.139056,231.271216
243,2023-01-03 13:00:00,8.2922,1,0,0,selllong,NaN,275.823723
244,2023-01-06 12:00:00,9.6188,1,1,1,buylong,0.192376,275.823723
245,2023-01-18 09:00:00,11.9094,1,0,0,selllong,NaN,341.507781
246,2023-01-25 15:00:00,11.9691,1,1,1,buylong,0.239382,341.507781
247,2023-01-27 10:00:00,11.6950,1,1,0,selllong,-0.034718,333.687035

In [317]:
def estatisticas_index(df):
    serie = df["index"].dropna()

    maximo = serie.max()
    minimo = serie.min()
    media = serie.mean()
    desvio = serie.std()
    taxagantot = (maximo - minimo)/minimo

    df["datetime"] = pd.to_datetime(df["datetime"])
    data_inicial = df["datetime"].min()
    data_final = df["datetime"].max()
    dias = (data_final - data_inicial).days
    

    taxagananualprom = (1 + taxagantot) ** (1 / dias * 365) - 1  
    taxalivrerisgoprom = 0.05
    sharpe = taxagananualprom/taxalivrerisgoprom
   
    return pd.Series({
        "Máximo": f"{maximo:.2f}",
        "Mínimo ": f"{minimo:.2f}",
        "Média": f"{media:.2f}",
        "Desvio padrão ": f"{desvio:.2f}",
        "Taxa de ganancia total ": f"{taxagantot * 100:.2f}%",
        "Taxa de ganancia anual prom ": f"{taxagananualprom * 100:.2f}%",
        "coef Sharpe": f"{sharpe:.2f}",
    })

In [319]:
resultado_index = estatisticas_index(df)
print(resultado_index.to_string())

Máximo                           341.51
Mínimo                           100.00
Média                            213.53
Desvio padrão                     53.53
Taxa de ganancia total          241.51%
Taxa de ganancia anual prom      13.97%
coef Sharpe                        2.79

In [257]:
def datas_drawdown_max(df):
    df = df.copy()
    df = df[df["index"].notna()]
    df["datetime"] = pd.to_datetime(df["datetime"])

    # Série com índice acumulado
    acumulado = df["index"]
    pico = acumulado.cummax()
    drawdown = acumulado - pico

    # Índice do drawdown máximo
    idx_vale = drawdown.idxmin()
    idx_pico = (acumulado[:idx_vale]).idxmax()

    # Datas correspondentes
    data_pico = df.loc[idx_pico, "datetime"]
    data_vale = df.loc[idx_vale, "datetime"]

    # Diferença percentual
    valor_pico = df.loc[idx_pico, "index"]
    valor_vale = df.loc[idx_vale, "index"]
    drawdown_pct = ((valor_vale - valor_pico) / valor_pico) * 100

    return pd.Series({
        "Data do Pico": data_pico.strftime("%Y-%m-%d %H:%M"),
        "Data do Vale": data_vale.strftime("%Y-%m-%d %H:%M"),
        "Valor do Pico": round(valor_pico, 2),
        "Valor do Vale": round(valor_vale, 2),
        "Drawdown Máximo (%)": f"{drawdown_pct:.2f}%"
    })

In [259]:
resultado_datas = datas_drawdown_max(df)
print(resultado_datas)

Data do Pico           2017-12-13 15:00
Data do Vale           2022-08-31 12:00
Valor do Pico                    264.73
Valor do Vale                    125.39
Drawdown Máximo (%)             -52.63%
dtype: object