System construction and test

In [2]:
from datetime import date, datetime
import pandas as pd
import yfinance as yf
import time
#from Alert import Alert
pd.options.mode.chained_assignment = None  # default='warn'
#alert = Alert('1h','GGAL')

input:
    
     Titulo  : example: GGAL
     frequencia de tick : 1h (frequencia mais alta)
     dftitulo : vista do BD sqtitulosalpha.bd (testar ultimos periodas)
Parametros a variar para back testing ( definir rangos de variação)
     k, d, smooth (parametros do stch)
     dayM  (frequencia media) (multiplicador da frequencia mais alta) exemplo: 5
     semM  (frequencia baixa) (multiplicador da frequencia media) exemplo: 7

In [5]:
dataini = '2022-04-03 19:30:00'
datafim = '2023-04-03 19:30:00'

In [7]:
import sqlite3
import pandas as pd

# Caminho para o banco de dados
caminho_bd = r'C:\Users\scitr\anaconda_projects\Trading_System\Dados_Fontes\Alpha_Vantage\sqtitulosalpha.db'

# Conectando ao banco
conexao = sqlite3.connect(caminho_bd)

# Lendo a view
#consulta = 'SELECT * FROM vwtitulosdados ORDER BY datetime'
consulta = f"""
SELECT * FROM vwtitulosdados
WHERE datetime BETWEEN '{dataini}' AND '{datafim}'
ORDER BY datetime
"""

dftitulosdados = pd.read_sql_query(consulta, conexao)

# Fechando a conexão
conexao.close()

# Exibindo os primeiros registros para conferir
display(dftitulosdados)

,symbol,moeda,intervalo,datetime,open,high,low,close,volume
0,GGAL,USD,60min,2022-04-04 09:00:00,8.9836,9.1457,8.9755,9.0079,45436.0
1,GGAL,USD,60min,2022-04-04 10:00:00,9.0484,9.0809,8.9755,8.9917,49030.0
2,GGAL,USD,60min,2022-04-04 11:00:00,8.9836,8.9998,8.9268,8.9268,41129.0
3,GGAL,USD,60min,2022-04-04 12:00:00,8.9268,9.0160,8.9268,8.9512,34248.0
4,GGAL,USD,60min,2022-04-04 13:00:00,8.9593,8.9593,8.8863,8.9187,67152.0
...,...,...,...,...,...,...,...,...,...
2101,GGAL,USD,60min,2023-04-03 12:00:00,9.5499,9.6357,9.5499,9.5756,29258.0
2102,GGAL,USD,60min,2023-04-03 13:00:00,9.5671,9.6872,9.5671,9.6700,48527.0
2103,GGAL,USD,60min,2023-04-03 14:00:00,9.6785,9.7447,9.6529,9.7301,32877.0
2104,GGAL,USD,60min,2023-04-03 15:00:00,9.7386,9.7816,9.6529,9.7558,143309.0
2105,GGAL,USD,60min,2023-04-03 16:00:00,9.7472,9.7472,9.7472,9.7472,13155.0

In [9]:

i = 'high'
K = 16  
D = 5    
smoth = 5  
dayM = 8  
semM = 4

In [11]:

# Stochastic calculation
def stochastic(df, i, K, D, smoth):
        
    df["k"] = (100. * (df.close - df.low.rolling(K).min()) /
        (df.high.rolling(K).max() - df.low.rolling(K).min()))
    
    df["k" + i] = df.k.rolling(smoth).mean()
    df["d" + i] = df["k" + i].rolling(D).mean()
    
    df.drop(columns=["k"], inplace=True)  

    return df
dfstoch = stochastic(dftitulosdados, i, K, D, smoth)
display (dfstoch)

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,khigh,dhigh
0,GGAL,USD,60min,2022-04-04 09:00:00,8.9836,9.1457,8.9755,9.0079,45436.0,NaN,NaN
1,GGAL,USD,60min,2022-04-04 10:00:00,9.0484,9.0809,8.9755,8.9917,49030.0,NaN,NaN
2,GGAL,USD,60min,2022-04-04 11:00:00,8.9836,8.9998,8.9268,8.9268,41129.0,NaN,NaN
3,GGAL,USD,60min,2022-04-04 12:00:00,8.9268,9.0160,8.9268,8.9512,34248.0,NaN,NaN
4,GGAL,USD,60min,2022-04-04 13:00:00,8.9593,8.9593,8.8863,8.9187,67152.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2101,GGAL,USD,60min,2023-04-03 12:00:00,9.5499,9.6357,9.5499,9.5756,29258.0,35.345039,24.486408
2102,GGAL,USD,60min,2023-04-03 13:00:00,9.5671,9.6872,9.5671,9.6700,48527.0,43.814248,30.270650
2103,GGAL,USD,60min,2023-04-03 14:00:00,9.6785,9.7447,9.6529,9.7301,32877.0,53.958531,37.149336
2104,GGAL,USD,60min,2023-04-03 15:00:00,9.7386,9.7816,9.6529,9.7558,143309.0,64.423364,45.395125
2105,GGAL,USD,60min,2023-04-03 16:00:00,9.7472,9.7472,9.7472,9.7472,13155.0,69.770972,53.462431

In [14]:
def set_test( df, intervalo, k, d, smth, dayM, semM):
        
        # Convert time
        #df["time"] = pd.to_datetime(df.index, utc=True)
        #df['timeArg'] = df['time'].dt.tz_convert('America/Argentina/Buenos_Aires')        
        #df['time'] = df['time'].dt.tz_convert(None)

        df = stochastic(df, "high", k, d, smth)
        df = stochastic(df, "med", k*dayM, d*dayM, smth*dayM)
        df = stochastic(df, "low", k*dayM*semM, d*dayM*semM, smth*dayM*semM)
    
        return df

dfstoch_hml= set_test(dfstoch, i , K, D, smoth, dayM , semM )
#%time set_test(dfstoch, i , K, D, smoth, dayM , semM )

In [35]:

def long_buy_crits( df):
    
    df["longbuylow"] = 0
    df["longbuymed"] = 0
    df["longbuyhigh"] = 0
    df["longselllow"] = 0
    df["longsellmed"] = 0
    df["longsellhigh"] = 0
    df["prices"] = 0.0
    df["state"] = ""    
    
    
    #for i in df.index: 
    for i in range(1, len(df)):
        
        # long buy  stochs criterias
        
        if df.loc[i,"klow"] > 20 and df.loc[i,"klow"] > df.loc[i,"dlow"] :
            df.loc[i, "longbuylow"] = 1
        else :
            df.loc[i, "longbuylow"] = 0
            
            
        if df.loc[i,"kmed"] > 20 and df.loc[i,"kmed"] > df.loc[i,"dmed"] :
            df.loc[i, "longbuymed"] = 1
        else :
            df.loc[i, "longbuymed"] = 0
            
    
        if df.loc[i,"khigh"] > 20 and df.loc[i,"khigh"] > df.loc[i,"dhigh"] :
            df.loc[i, "longbuyhigh"] = 1
        else :
            df.loc[i, "longbuyhigh"] = 0

        # long buy  states and prices          

        if  df.loc[i, "longbuyhigh"] == 1 and df.loc[i, "longbuymed"] == 1 and df.loc[i, "longbuylow"] == 1 and df.loc[i-1, "state"] == "" :        
            df.loc[i, "state"] = "buylong"            
            
        
        if  df.loc[i, "longbuymed"] == 1 and df.loc[i, "longbuylow"] == 1 and (df.loc[i-1, "state"] == "buylong" or df.loc[i-1, "state"] == "staylong") :
            df.loc[i, "state"] = "staylong" 

        # long sell state and price 

        if  df.loc[i, "longbuyhigh"] == 0 and df.loc[i, "longbuymed"] == 0 and   (df.loc[i-1, "state"] == "buylong" or df.loc[i-1, "state"] == "staylong")  : 
             df.loc[i, "state"] = "selllong"

        
         # Short buy stoch criterias
        
        if df.loc[i,"klow"] < 80 and  df.loc[i,"klow"] < df.loc[i,"dlow"] :
            df.loc[i, "longselllow"] = 1
        else :
            df.loc[i, "longselllow"] = 0
            
            
        if df.loc[i,"kmed"] < 80 and df.loc[i,"kmed"] < df.loc[i,"dmed"] :
            df.loc[i, "longsellmed"] = 1
        else :
            df.loc[i, "longsellmed"] = 0
            
    
        if df.loc[i,"khigh"] < 80 and df.loc[i,"khigh"] < df.loc[i,"dhigh"] :
            df.loc[i, "longsellhigh"] = 1
        else :
            df.loc[i, "longsellhigh"] = 0

            
    return df

df = long_buy_crits(dfstoch_hml) 

#%time long_buy_crits(dfstoch_hml)   
#display (df)

In [37]:

#df_filtrado = df[(df["buylong"] == 1)]  # & (df["longenter"] == 1)]
#
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)  # Mostra o conteúdo completo da
#display(df.head(500))
df_intervalo = df.iloc[840:1000]
display(df_intervalo)

,symbol,moeda,intervalo,datetime,open,high,low,close,volume,khigh,...,klow,dlow,longbuylow,longbuymed,longbuyhigh,longselllow,longsellmed,longsellhigh,state,prices
840,GGAL,USD,60min,2022-08-24 15:00:00,7.1317,7.2413,7.1317,7.1991,169881.0,80.216274,...,56.899187,34.323680,1,0,1,0,1,0,,0.0
841,GGAL,USD,60min,2022-08-24 16:00:00,7.2076,7.2076,7.2076,7.2076,11666.0,85.546558,...,57.087061,34.613242,1,0,1,0,1,0,,0.0
842,GGAL,USD,60min,2022-08-25 09:00:00,7.2244,7.2834,7.0052,7.0305,97477.0,79.852671,...,57.206129,34.901979,1,0,1,0,1,0,,0.0
843,GGAL,USD,60min,2022-08-25 10:00:00,7.0390,7.1401,6.9741,7.1321,120547.0,76.244682,...,57.326615,35.189773,1,0,0,0,1,1,,0.0
844,GGAL,USD,60min,2022-08-25 11:00:00,7.1486,7.2160,7.1015,7.1486,49391.0,72.070176,...,57.482063,35.476844,1,0,0,0,1,1,,0.0
845,GGAL,USD,60min,2022-08-25 12:00:00,7.1486,7.2076,7.1486,7.1738,21956.0,68.923165,...,57.617254,35.763071,1,0,0,0,1,1,,0.0
846,GGAL,USD,60min,2022-08-25 13:00:00,7.1907,7.2413,7.1631,7.1738,60670.0,65.402692,...,57.746119,36.048152,1,0,0,0,1,1,,0.0
847,GGAL,USD,60min,2022-08-25 14:00:00,7.1654,7.3087,7.1654,7.2750,103386.0,75.488894,...,57.911141,36.332298,1,0,1,0,1,0,,0.0
848,GGAL,USD,60min,2022-08-25 15:00:00,7.2708,7.3762,7.2708,7.3593,147072.0,81.756426,...,58.099427,36.615915,1,0,1,0,1,0,,0.0
849,GGAL,USD,60min,2022-08-25 16:00:00,7.3509,7.3509,7.3509,7.3509,17316.0,86.954724,...,58.294733,36.899034,1,1,1,0,0,0,buylong,0.0
850,GGAL,USD,60min,2022-08-26 09:00:00,7.3509,7.5195,7.3509,7.5110,83287.0,91.663618,...,58.510426,37.181736,1,1,1,0,0,0,staylong,0.0
851,GGAL,USD,60min,2022-08-26 10:00:00,7.4942,7.5700,7.3677,7.3930,199861.0,90.724165,...,58.657803,37.463350,1,1,1,0,0,0,staylong,0.0
852,GGAL,USD,60min,2022-08-26 11:00:00,7.3762,7.3846,7.2497,7.3087,72682.0,83.408077,...,58.826524,37.744280,1,1,0,0,0,0,staylong,0.0
853,GGAL,USD,60min,2022-08-26 12:00:00,7.2919,7.3424,7.2919,7.3340,94772.0,76.123700,...,59.013078,38.024718,1,1,0,0,0,1,staylong,0.0
854,GGAL,USD,60min,2022-08-26 13:00:00,7.3340,7.3762,7.3327,7.3762,132450.0,70.571992,...,59.211447,38.304756,1,1,0,0,0,1,staylong,0.0
855,GGAL,USD,60min,2022-08-26 14:00:00,7.3762,7.4225,7.3753,7.4225,98221.0,65.913744,...,59.417704,38.584310,1,1,0,0,0,1,staylong,0.0
856,GGAL,USD,60min,2022-08-26 15:00:00,7.4225,7.4436,7.3551,7.3593,182542.0,64.782682,...,59.639509,38.863626,1,1,0,0,0,1,staylong,0.0
857,GGAL,USD,60min,2022-08-26 16:00:00,7.3677,7.3677,7.3677,7.3677,13489.0,66.762880,...,59.844040,39.142430,1,1,0,0,0,1,staylong,0.0
858,GGAL,USD,60min,2022-08-29 09:00:00,7.2413,7.3846,7.2413,7.3340,95477.0,66.762880,...,60.027440,39.420543,1,1,0,0,0,1,staylong,0.0
859,GGAL,USD,60min,2022-08-29 10:00:00,7.3087,7.4183,7.3003,7.4183,187559.0,66.791340,...,60.239181,39.698281,1,1,1,0,0,0,staylong,0.0
860,GGAL,USD,60min,2022-08-29 11:00:00,7.4267,7.5532,7.4183,7.5363,173024.0,70.142404,...,60.484569,39.975896,1,1,1,0,0,0,staylong,0.0
861,GGAL,USD,60min,2022-08-29 12:00:00,7.5279,7.5953,7.5110,7.5869,109857.0,76.825352,...,60.724497,40.253215,1,1,1,0,0,0,staylong,0.0
862,GGAL,USD,60min,2022-08-29 13:00:00,7.5985,7.6122,7.5363,7.5700,105631.0,81.726093,...,60.951486,40.530096,1,1,1,0,0,0,staylong,0.0
863,GGAL,USD,60min,2022-08-29 14:00:00,7.5658,7.5996,7.4773,7.5279,213432.0,85.101185,...,61.173005,40.806779,1,1,1,0,0,0,staylong,0.0
864,GGAL,USD,60min,2022-08-29 15:00:00,7.5279,7.5321,7.3087,7.3171,187790.0,75.664528,...,61.349772,41.082931,1,1,0,0,0,1,staylong,0.0
865,GGAL,USD,60min,2022-08-29 16:00:00,7.3171,7.3171,7.3171,7.3171,6657.0,61.351313,...,61.524962,41.358383,1,1,0,0,0,1,staylong,0.0
866,GGAL,USD,60min,2022-08-30 07:00:00,7.5532,7.5532,7.5532,7.5532,167.0,58.558572,...,61.746762,41.633360,1,1,0,0,0,1,staylong,0.0
867,GGAL,USD,60min,2022-08-30 09:00:00,7.3003,7.4014,7.1401,7.2160,102847.0,43.662980,...,61.903065,41.907413,1,1,0,0,0,1,staylong,0.0
868,GGAL,USD,60min,2022-08-30 10:00:00,7.2329,7.3424,7.1991,7.3340,120442.0,36.423041,...,62.075191,42.180555,1,1,0,0,0,1,staylong,0.0
869,GGAL,USD,60min,2022-08-30 11:00:00,7.3416,7.3677,7.3070,7.3424,59068.0,40.905905,...,62.276390,42.453133,1,1,0,0,0,1,staylong,0.0
870,GGAL,USD,60min,2022-08-30 12:00:00,7.3424,7.3930,7.2632,7.2666,57456.0,42.177584,...,62.458452,42.724932,1,1,0,0,0,1,staylong,0.0
871,GGAL,USD,60min,2022-08-30 13:00:00,7.2643,7.3171,7.2345,7.3020,45869.0,32.217750,...,62.650756,42.995998,1,1,0,0,0,1,staylong,0.0
872,GGAL,USD,60min,2022-08-30 14:00:00,7.3087,7.3171,7.1569,7.1738,115472.0,30.429994,...,62.817324,43.266266,1,1,0,0,0,1,staylong,0.0
873,GGAL,USD,60min,2022-08-30 15:00:00,7.1696,7.2076,7.1486,7.1570,103646.0,22.931582,...,62.969239,43.535707,1,1,0,0,0,1,staylong,0.0
874,GGAL,USD,60min,2022-08-30 16:00:00,7.1570,7.1570,7.1570,7.1570,7555.0,15.077314,...,63.089507,43.804014,1,1,0,0,0,1,staylong,0.0
875,GGAL,USD,60min,2022-08-31 09:00:00,7.1148,7.1823,7.0052,7.1317,51082.0,13.886320,...,63.233454,44.071342,1,1,0,0,0,1,staylong,0.0
876,GGAL,USD,60min,2022-08-31 10:00:00,7.1361,7.2581,7.1233,7.1738,35909.0,12.582793,...,63.416801,44.337999,1,1,0,0,0,1,staylong,0.0
877,GGAL,USD,60min,2022-08-31 11:00:00,7.1654,7.1690,7.0162,7.0558,72832.0,12.822345,...,63.594823,44.603992,1,1,0,0,0,1,staylong,0.0
878,GGAL,USD,60min,2022-08-31 12:00:00,7.0558,7.0769,7.0221,7.0263,26394.0,12.816354,...,63.775674,44.869372,1,0,0,0,0,1,selllong,0.0
879,GGAL,USD,60min,2022-08-31 13:00:00,7.0288,7.0305,6.9294,6.9462,97224.0,12.639039,...,63.948706,45.134159,1,0,0,0,0,1,,0.0
880,GGAL,USD,60min,2022-08-31 14:00:00,6.9462,6.9462,6.8324,6.8619,109211.0,9.289534,...,64.108220,45.398524,1,0,0,0,1,1,,0.0
881,GGAL,USD,60min,2022-08-31 15:00:00,6.8619,6.9209,6.8366,6.8409,113029.0,3.970194,...,64.258238,45.662025,1,0,0,0,1,1,,0.0
882,GGAL,USD,60min,2022-08-31 16:00:00,6.8366,6.8366,6.8366,6.8366,55607.0,2.450605,...,64.408880,45.924626,1,0,0,0,1,1,,0.0
883,GGAL,USD,60min,2022-09-01 09:00:00,6.8282,6.8704,6.6765,6.7439,51340.0,3.622013,...,64.554390,46.186410,1,0,0,0,1,1,,0.0
884,GGAL,USD,60min,2022-09-01 10:00:00,6.7271,6.8451,6.7186,6.8198,57716.0,7.083379,...,64.698062,46.447285,1,0,0,0,1,0,,0.0
885,GGAL,USD,60min,2022-09-01 11:00:00,6.8114,6.9209,6.7861,6.8957,44193.0,12.383476,...,64.847028,46.707318,1,0,0,0,1,0,,0.0
886,GGAL,USD,60min,2022-09-01 12:00:00,6.9108,6.9589,6.9108,6.9294,24657.0,20.043350,...,65.015474,46.966662,1,0,1,0,1,0,,0.0
887,GGAL,USD,60min,2022-09-01 13:00:00,6.9226,6.9884,6.9226,6.9547,22268.0,28.581330,...,65.179353,47.225213,1,0,1,0,1,0,,0.0
888,GGAL,USD,60min,2022-09-01 14:00:00,6.9462,6.9968,6.9396,6.9547,22632.0,36.266675,...,65.343232,47.482972,1,0,1,0,1,0,,0.0
889,GGAL,USD,60min,2022-09-01 15:00:00,6.9547,7.0137,6.9294,6.9715,131482.0,42.411104,...,65.503794,47.739806,1,0,1,0,1,0,,0.0
890,GGAL,USD,60min,2022-09-01 16:00:00,6.9884,6.9884,6.9884,6.9884,52986.0,47.018056,...,65.661851,47.995770,1,0,1,0,1,0,,0.0
891,GGAL,USD,60min,2022-09-02 09:00:00,7.0895,7.0895,6.9041,7.0474,84421.0,51.876804,...,65.833245,48.251000,1,0,1,0,1,0,,0.0
892,GGAL,USD,60min,2022-09-02 10:00:00,7.0474,7.2666,7.0390,7.2455,69997.0,62.476064,...,66.041496,48.505676,1,0,1,0,1,0,,0.0
893,GGAL,USD,60min,2022-09-02 11:00:00,7.2497,7.2666,7.1233,7.2160,36861.0,71.194388,...,66.222507,48.759561,1,0,1,0,1,0,,0.0
894,GGAL,USD,60min,2022-09-02 12:00:00,7.2160,7.3087,7.1486,7.2860,155519.0,80.331831,...,66.408267,49.012640,1,0,1,0,1,0,,0.0
895,GGAL,USD,60min,2022-09-02 13:00:00,7.2834,7.3257,7.1949,7.1949,80189.0,85.576672,...,66.576606,49.264849,1,0,1,0,1,0,,0.0
896,GGAL,USD,60min,2022-09-02 14:00:00,7.1991,7.2413,7.1949,7.2286,19145.0,89.830827,...,66.755717,49.516275,1,0,1,0,1,0,,0.0
897,GGAL,USD,60min,2022-09-02 15:00:00,7.2329,7.2961,7.1738,7.1907,162829.0,86.386996,...,66.929432,49.766702,1,0,1,0,1,0,,0.0
898,GGAL,USD,60min,2022-09-02 16:00:00,7.1991,7.1991,7.1991,7.1991,27641.0,84.201774,...,67.093972,50.016136,1,0,0,0,1,0,,0.0
899,GGAL,USD,60min,2022-09-06 08:00:00,7.4520,7.4520,7.3340,7.3424,1700.0,81.931082,...,67.290904,50.264708,1,0,0,0,1,0,,0.0
900,GGAL,USD,60min,2022-09-06 09:00:00,7.2750,7.3416,7.2076,7.2876,179197.0,81.022979,...,67.494425,50.512598,1,0,0,0,1,0,,0.0
901,GGAL,USD,60min,2022-09-06 10:00:00,7.2244,7.4267,7.2244,7.4267,121855.0,83.090827,...,67.734137,50.760031,1,0,0,0,1,0,,0.0
902,GGAL,USD,60min,2022-09-06 11:00:00,7.4183,7.4773,7.4014,7.4352,79110.0,85.780845,...,67.986844,51.007159,1,0,1,0,1,0,,0.0
903,GGAL,USD,60min,2022-09-06 12:00:00,7.4352,7.4436,7.2076,7.2160,103502.0,80.563793,...,68.197925,51.253740,1,0,0,0,1,0,,0.0
904,GGAL,USD,60min,2022-09-06 13:00:00,7.2160,7.2834,7.1738,7.2834,39463.0,76.787086,...,68.428201,51.499929,1,0,0,0,1,1,,0.0
905,GGAL,USD,60min,2022-09-06 14:00:00,7.2834,7.3340,7.2834,7.3340,24044.0,76.724764,...,68.669107,51.745645,1,0,0,0,1,1,,0.0
906,GGAL,USD,60min,2022-09-06 15:00:00,7.3256,7.3424,7.2497,7.3087,102117.0,71.765527,...,68.901142,51.990955,1,0,0,0,1,1,,0.0
907,GGAL,USD,60min,2022-09-06 16:00:00,7.3171,7.3171,7.3171,7.3171,17480.0,65.924412,...,69.136651,52.235890,1,0,0,0,1,1,,0.0
908,GGAL,USD,60min,2022-09-07 09:00:00,7.3087,7.3171,7.2329,7.2792,75676.0,63.849558,...,69.352520,52.480214,1,0,0,0,1,1,,0.0
909,GGAL,USD,60min,2022-09-07 10:00:00,7.2624,7.5448,7.2624,7.5153,172288.0,69.125938,...,69.620161,52.724285,1,0,0,0,1,1,,0.0
910,GGAL,USD,60min,2022-09-07 11:00:00,7.5195,7.6166,7.5110,7.5616,132942.0,71.641746,...,69.891737,52.968078,1,0,1,0,1,0,,0.0
911,GGAL,USD,60min,2022-09-07 12:00:00,7.5532,7.5532,7.4605,7.5490,40567.0,74.471212,...,70.178695,53.211765,1,0,1,0,1,0,,0.0
912,GGAL,USD,60min,2022-09-07 13:00:00,7.5616,7.6998,7.5532,7.6965,204346.0,81.655799,...,70.486662,53.455516,1,0,1,0,1,0,,0.0
913,GGAL,USD,60min,2022-09-07 14:00:00,7.6965,7.7134,7.5490,7.5616,93696.0,87.221499,...,70.774770,53.699188,1,0,1,0,1,0,,0.0
914,GGAL,USD,60min,2022-09-07 15:00:00,7.5574,7.6712,7.5532,7.6038,205886.0,84.648378,...,71.072080,53.942981,1,0,1,0,1,0,,0.0
915,GGAL,USD,60min,2022-09-07 16:00:00,7.6122,7.6712,7.6122,7.6122,22082.0,83.381643,...,71.372798,54.186940,1,0,1,0,1,0,,0.0
916,GGAL,USD,60min,2022-09-08 09:00:00,7.6206,7.7639,7.5237,7.7471,100965.0,85.865545,...,71.693561,54.431215,1,0,1,0,1,0,,0.0
917,GGAL,USD,60min,2022-09-08 10:00:00,7.7471,7.7977,7.4183,7.4520,133977.0,74.909116,...,71.925718,54.675158,1,0,0,0,1,1,,0.0
918,GGAL,USD,60min,2022-09-08 11:00:00,7.4436,7.5532,7.3930,7.4352,90604.0,68.915054,...,72.132168,54.918528,1,1,0,0,0,1,,0.0
919,GGAL,USD,60min,2022-09-08 12:00:00,7.4352,7.4773,7.2834,7.4635,111439.0,62.264067,...,72.360436,55.161541,1,1,0,0,0,1,,0.0
920,GGAL,USD,60min,2022-09-08 13:00:00,7.4773,7.4857,7.3762,7.4857,62110.0,54.966835,...,72.591341,55.404211,1,1,0,0,0,1,,0.0
921,GGAL,USD,60min,2022-09-08 14:00:00,7.4857,7.4857,7.4099,7.4267,65082.0,42.398836,...,72.811813,55.646694,1,1,0,0,0,1,,0.0
922,GGAL,USD,60min,2022-09-08 15:00:00,7.4267,7.5321,7.3939,7.5237,224862.0,43.778191,...,73.038587,55.888941,1,1,0,0,0,1,,0.0
923,GGAL,USD,60min,2022-09-08 16:00:00,7.5195,7.5195,7.5195,7.5195,13895.0,45.547368,...,73.269219,56.131025,1,1,0,0,0,1,,0.0
924,GGAL,USD,60min,2022-09-09 09:00:00,7.6038,7.6459,7.5041,7.5201,47340.0,45.888869,...,73.498069,56.372870,1,1,0,0,0,1,,0.0
925,GGAL,USD,60min,2022-09-09 10:00:00,7.5279,7.6501,7.5279,7.5514,45024.0,47.358960,...,73.728196,56.614391,1,1,1,0,0,0,buylong,0.0
926,GGAL,USD,60min,2022-09-09 11:00:00,7.5532,7.5532,7.4773,7.5279,56610.0,50.004423,...,73.946823,56.855448,1,1,1,0,0,0,staylong,0.0
927,GGAL,USD,60min,2022-09-09 12:00:00,7.5279,7.5363,7.4857,7.5279,109657.0,49.215042,...,74.168720,57.096113,1,1,1,0,0,0,staylong,0.0
928,GGAL,USD,60min,2022-09-09 13:00:00,7.5279,7.7049,7.5279,7.6819,149316.0,54.563109,...,74.421594,57.336535,1,1,1,0,0,0,staylong,0.0
929,GGAL,USD,60min,2022-09-09 14:00:00,7.6881,7.8904,7.6796,7.8735,264200.0,64.378026,...,74.689003,57.576907,1,1,1,0,0,0,staylong,0.0
930,GGAL,USD,60min,2022-09-09 15:00:00,7.8735,8.0632,7.8651,8.0168,485396.0,72.766045,...,74.949239,57.817047,1,1,1,0,0,0,staylong,0.0
931,GGAL,USD,60min,2022-09-09 16:00:00,8.0210,8.0253,8.0210,8.0253,15995.0,82.285931,...,75.188401,58.056650,1,1,1,0,0,0,staylong,0.0
932,GGAL,USD,60min,2022-09-12 09:00:00,8.2023,8.3540,8.0337,8.0674,117018.0,87.423855,...,75.384545,58.295497,1,1,1,0,0,0,staylong,0.0
933,GGAL,USD,60min,2022-09-12 10:00:00,8.0674,8.0674,7.8904,7.8988,207487.0,83.423420,...,75.549828,58.533400,1,1,1,0,0,0,staylong,0.0
934,GGAL,USD,60min,2022-09-12 11:00:00,7.9072,7.9157,7.8145,7.8735,160275.0,75.003982,...,75.713854,58.770327,1,1,0,0,0,1,staylong,0.0
935,GGAL,USD,60min,2022-09-12 12:00:00,7.8651,7.8820,7.7977,7.8314,153710.0,65.504728,...,75.878546,59.006316,1,1,0,0,0,1,staylong,0.0
936,GGAL,USD,60min,2022-09-12 13:00:00,7.8314,7.8650,7.8061,7.8650,134114.0,56.290334,...,76.044329,59.241346,1,1,0,0,0,1,staylong,0.0
937,GGAL,USD,60min,2022-09-12 14:00:00,7.8693,7.9915,7.8693,7.9705,72576.0,53.655590,...,76.214221,59.475190,1,1,0,0,0,1,staylong,0.0
938,GGAL,USD,60min,2022-09-12 15:00:00,7.9663,7.9831,7.8145,7.9157,271395.0,52.160373,...,76.364552,59.707580,1,1,0,0,0,1,staylong,0.0
939,GGAL,USD,60min,2022-09-12 16:00:00,7.8988,7.8988,7.8988,7.8988,16159.0,50.752252,...,76.506992,59.938494,1,1,0,0,0,1,staylong,0.0
940,GGAL,USD,60min,2022-09-13 09:00:00,7.7977,7.9810,7.7049,7.9241,120756.0,51.634323,...,76.645617,60.167767,1,1,0,0,0,1,staylong,0.0
941,GGAL,USD,60min,2022-09-13 10:00:00,7.8988,8.1096,7.7808,7.8145,176925.0,49.513245,...,76.756714,60.395134,1,1,0,0,0,1,staylong,0.0
942,GGAL,USD,60min,2022-09-13 11:00:00,7.8314,7.8314,7.6712,7.6881,72091.0,42.163979,...,76.845283,60.620460,1,1,0,0,0,1,staylong,0.0
943,GGAL,USD,60min,2022-09-13 12:00:00,7.6796,7.7471,7.6291,7.6291,81843.0,34.612905,...,76.923337,60.843672,1,1,0,0,0,1,staylong,0.0
944,GGAL,USD,60min,2022-09-13 13:00:00,7.6291,7.7218,7.6248,7.7049,47844.0,27.194229,...,77.026322,61.064989,1,1,0,0,0,1,staylong,0.0
945,GGAL,USD,60min,2022-09-13 14:00:00,7.7091,7.7471,7.6459,7.6699,79478.0,18.238433,...,77.139581,61.284578,1,1,0,0,0,1,staylong,0.0
946,GGAL,USD,60min,2022-09-13 15:00:00,7.6712,7.6796,7.5616,7.5953,140996.0,11.396530,...,77.242603,61.502464,1,1,0,0,0,1,staylong,0.0
947,GGAL,USD,60min,2022-09-13 16:00:00,7.5953,7.5953,7.5953,7.5953,17439.0,7.585128,...,77.326055,61.718383,1,1,0,0,0,1,staylong,0.0
948,GGAL,USD,60min,2022-09-14 09:00:00,7.5869,7.7218,7.5785,7.6586,83056.0,8.675207,...,77.423227,61.932399,1,1,0,0,0,1,staylong,0.0
949,GGAL,USD,60min,2022-09-14 10:00:00,7.6670,7.7724,7.6291,7.7471,68489.0,13.248352,...,77.532087,62.144633,1,1,0,0,0,0,staylong,0.0
950,GGAL,USD,60min,2022-09-14 11:00:00,7.7471,7.7977,7.7302,7.7386,61599.0,18.471234,...,77.642704,62.355138,1,1,0,0,0,0,staylong,0.0
951,GGAL,USD,60min,2022-09-14 12:00:00,7.7471,7.7892,7.7302,7.7639,30831.0,25.003865,...,77.759456,62.563977,1,1,1,0,0,0,staylong,0.0
952,GGAL,USD,60min,2022-09-14 13:00:00,7.7724,7.8229,7.7218,7.7386,40285.0,30.613139,...,77.870073,62.771156,1,1,1,0,0,0,staylong,0.0
953,GGAL,USD,60min,2022-09-14 14:00:00,7.7386,7.7639,7.7218,7.7218,33243.0,32.919708,...,77.992389,62.976840,1,0,1,0,1,0,,0.0
954,GGAL,USD,60min,2022-09-14 15:00:00,7.7260,7.7808,7.6796,7.7808,60566.0,34.149635,...,78.128472,63.181293,1,0,1,0,1,0,,0.0
955,GGAL,USD,60min,2022-09-14 16:00:00,7.7808,7.7808,7.7808,7.7808,17515.0,35.689781,...,78.259657,63.384287,1,0,1,0,1,0,,0.0
956,GGAL,USD,60min,2022-09-15 09:00:00,7.8145,7.8735,7.7639,7.8229,28854.0,37.843066,...,78.409767,63.586099,1,0,1,0,1,0,,0.0
957,GGAL,USD,60min,2022-09-15 10:00:00,7.8179,7.8735,7.6375,7.6628,79516.0,37.872471,...,78.526465,63.786437,1,0,1,0,1,0,,0.0
958,GGAL,USD,60min,2022-09-15 11:00:00,7.6631,7.6796,7.5785,7.6122,70801.0,35.270385,...,78.634958,63.985283,1,0,0,0,1,1,,0.0
959,GGAL,USD,60min,2022-09-15 12:00:00,7.6206,7.6670,7.5886,7.6206,43009.0,31.053649,...,78.744135,64.182652,1,0,0,0,1,1,,0.0
960,GGAL,USD,60min,2022-09-15 13:00:00,7.6206,7.6206,7.4857,7.4942,73256.0,23.492020,...,78.832411,64.378546,1,0,0,0,1,1,,0.0
961,GGAL,USD,60min,2022-09-15 14:00:00,7.4942,7.5218,7.4436,7.4520,98072.0,14.346312,...,78.906641,64.572862,1,0,0,0,1,1,,0.0
962,GGAL,USD,60min,2022-09-15 15:00:00,7.4543,7.4857,7.4267,7.4773,94885.0,10.122048,...,78.983832,64.765619,1,0,0,0,1,1,,0.0
963,GGAL,USD,60min,2022-09-15 16:00:00,7.4773,7.4773,7.4773,7.4773,59250.0,9.142414,...,79.077245,64.957020,1,0,0,0,1,1,,0.0
964,GGAL,USD,60min,2022-09-16 09:00:00,7.3509,7.3762,7.3004,7.3298,16626.0,6.385149,...,79.137033,65.146976,1,0,0,0,1,1,,0.0
965,GGAL,USD,60min,2022-09-16 10:00:00,7.3214,7.5363,7.3214,7.5110,59472.0,13.296281,...,79.219321,65.335665,1,0,0,0,1,0,,0.0
966,GGAL,USD,60min,2022-09-16 11:00:00,7.5043,7.5384,7.4352,7.4689,58467.0,18.785793,...,79.290853,65.523026,1,0,0,0,1,0,,0.0
967,GGAL,USD,60min,2022-09-16 12:00:00,7.4689,7.4796,7.4141,7.4689,38599.0,22.401097,...,79.364824,65.709123,1,0,1,0,1,0,,0.0
968,GGAL,USD,60min,2022-09-16 13:00:00,7.4689,7.4796,7.4352,7.4689,41645.0,26.016402,...,79.473059,65.894325,1,0,1,0,1,0,,0.0
969,GGAL,USD,60min,2022-09-16 14:00:00,7.4717,7.4857,7.4352,7.4773,36020.0,31.163846,...,79.598297,66.078914,1,0,1,0,1,0,,0.0
970,GGAL,USD,60min,2022-09-16 15:00:00,7.4815,7.4815,7.4352,7.4605,67029.0,29.401501,...,79.718915,66.262812,1,0,1,0,1,0,,0.0
971,GGAL,USD,60min,2022-09-16 16:00:00,7.4520,7.4520,7.4520,7.4520,18267.0,28.811726,...,79.834746,66.445959,1,0,1,0,1,0,,0.0
972,GGAL,USD,60min,2022-09-19 09:00:00,7.3677,7.5026,7.3340,7.4689,19696.0,28.811726,...,79.958487,66.628533,1,0,0,0,1,1,,0.0
973,GGAL,USD,60min,2022-09-19 10:00:00,7.4842,7.5532,7.4183,7.5363,40363.0,35.373409,...,80.098325,66.810690,1,0,1,0,1,0,,0.0
974,GGAL,USD,60min,2022-09-19 11:00:00,7.5448,7.5827,7.4942,7.5827,31528.0,44.600948,...,80.246452,66.992413,1,0,1,0,1,0,,0.0
975,GGAL,USD,60min,2022-09-19 12:00:00,7.5869,7.7091,7.5785,7.7091,13593.0,59.013790,...,80.418713,67.173863,1,0,1,0,1,0,,0.0
976,GGAL,USD,60min,2022-09-19 13:00:00,7.7091,7.7429,7.6543,7.7302,62443.0,73.149254,...,80.617830,67.355318,1,0,1,0,1,0,,0.0
977,GGAL,USD,60min,2022-09-19 14:00:00,7.7139,7.8061,7.7139,7.7513,32253.0,85.101661,...,80.812789,67.536686,1,0,1,0,1,0,,0.0
978,GGAL,USD,60min,2022-09-19 15:00:00,7.7492,7.8314,7.7302,7.8229,57494.0,92.339527,...,80.984116,67.717624,1,0,1,0,1,0,,0.0
979,GGAL,USD,60min,2022-09-19 16:00:00,7.8229,7.8229,7.8229,7.8229,43492.0,96.618395,...,81.137497,67.897895,1,0,1,0,1,0,,0.0
980,GGAL,USD,60min,2022-09-20 09:00:00,7.7555,7.7892,7.6628,7.6964,24959.0,91.324277,...,81.265895,68.077348,1,0,1,0,1,0,,0.0
981,GGAL,USD,60min,2022-09-20 10:00:00,7.6965,7.6965,7.5869,7.6628,27043.0,85.119036,...,81.385845,68.255807,1,0,0,0,1,0,,0.0
982,GGAL,USD,60min,2022-09-20 11:00:00,7.6663,7.7555,7.6543,7.7471,32247.0,83.896703,...,81.523278,68.433505,1,0,0,0,1,0,,0.0
983,GGAL,USD,60min,2022-09-20 12:00:00,7.7471,7.7977,7.7302,7.7555,14515.0,81.164984,...,81.661376,68.610505,1,0,0,0,1,0,,0.0
984,GGAL,USD,60min,2022-09-20 13:00:00,7.7555,7.7724,7.7386,7.7387,21201.0,77.757752,...,81.801377,68.786925,1,0,0,0,1,1,,0.0
985,GGAL,USD,60min,2022-09-20 14:00:00,7.7386,7.7555,7.6805,7.6805,19932.0,76.984318,...,81.931005,68.962817,1,0,0,0,1,1,,0.0
986,GGAL,USD,60min,2022-09-20 15:00:00,7.6881,7.7176,7.6543,7.6881,56934.0,78.001608,...,82.037520,69.137930,1,0,0,0,1,1,,0.0
987,GGAL,USD,60min,2022-09-20 16:00:00,7.6881,7.8229,7.6881,7.6881,29549.0,75.629272,...,82.132612,69.312125,1,0,0,0,1,1,,0.0
988,GGAL,USD,60min,2022-09-20 17:00:00,7.7977,7.7977,7.7555,7.7555,285.0,75.006487,...,82.241344,69.485379,1,0,0,0,1,1,,0.0
989,GGAL,USD,60min,2022-09-21 09:00:00,7.7555,7.7555,7.6628,7.7134,15055.0,71.735056,...,82.327879,69.657630,1,0,0,0,1,1,,0.0
990,GGAL,USD,60min,2022-09-21 10:00:00,7.7134,7.7134,7.4520,7.4689,71247.0,58.693487,...,82.367586,69.828604,1,0,0,0,1,1,,0.0
991,GGAL,USD,60min,2022-09-21 11:00:00,7.4773,7.5110,7.4436,7.4773,29653.0,46.193459,...,82.408790,69.998498,1,0,0,0,1,1,,0.0
992,GGAL,USD,60min,2022-09-21 12:00:00,7.4605,7.4605,7.4099,7.4267,33895.0,32.752574,...,82.427909,70.167053,1,0,0,0,1,1,,0.0