In [ ]:
Api busqueda de codigos por string

In [61]:
import requests
import pandas as pd

# Substitua a chave da API pelo seu próprio valor
url = 'https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=GGAL&apikey=BSFBG5DHV3CCXVMV'
r = requests.get(url)
data = r.json()

# Extraindo a lista de símbolos do JSON
symbols = data['bestMatches']

# Convertendo para um dataframe do pandas
df = pd.DataFrame(symbols)

# Renomeando colunas para algo mais intuitivo
df.columns = ['Símbolo', 'Nome', 'Tipo de Ativo', 'Região', 'Mercado Aberto', 'Mercado Fechado',  'Correspondência','Moeda','matchScore']

# Exibindo o dataframe
display(df)

,Símbolo,Nome,Tipo de Ativo,Região,Mercado Aberto,Mercado Fechado,Correspondência,Moeda,matchScore
0,GGAL,Grupo Financiero Galicia,Equity,United States,09:30,16:00,UTC-04,USD,1.0000

download um mes completo a partir da data month= (ex: 2009-02)

In [55]:
function = 'TIME_SERIES_INTRADAY'
symbol = 'GGAL'
interval = '60min'
month = '2009-02' 
apikey = 'BSFBG5DHV3CCXVMV'

In [57]:
import requests
import pandas as pd
# Construindo a URL dinamicamente
url = f'https://www.alphavantage.co/query?function={function}&symbol={symbol}&interval={interval}&month={month}&outputsize=full&apikey={apikey}'
r = requests.get(url)
data = r.json()
# Extraindo os dados do JSON
time_series = data.get(f'Time Series ({interval})', {})
# Convertendo para um dataframe do pandas
df = pd.DataFrame.from_dict(time_series, orient='index')

# Renomeando colunas para algo mais intuitivo
df.columns = ['Open', 'High', 'Low', 'Close', 'Volume']

# Adicionando a coluna DateTime
df.insert(0, 'DateTime', df.index)

# Convertendo a coluna DateTime para datetime
df['DateTime'] = pd.to_datetime(df['DateTime'])

# Ajustando o índice para ser a coluna DateTime
df = df.set_index('DateTime')

# Ordenando os dados pelo índice
df = df.sort_index()

# Exibindo o dataframe
display(df)
display(df.dtypes)

                       Open    High     Low   Close Volume
DateTime
2009-02-02 09:00:00  1.4065  1.4065  1.4065  1.4065    100
2009-02-02 10:00:00  1.5070  1.5070  1.4761  1.4761   6500
2009-02-02 15:00:00  1.4915  1.5302  1.4915  1.5302   1100
2009-02-03 13:00:00  1.5688  1.5688  1.5456  1.5456   2600
2009-02-03 14:00:00  1.5456  1.5534  1.5456  1.5456   1200
...                     ...     ...     ...     ...    ...
2009-02-27 12:00:00  1.3602  1.3602  1.3138  1.3524  37724
2009-02-27 13:00:00  1.3524  1.3756  1.3370  1.3679  55020
2009-02-27 14:00:00  1.3756  1.3833  1.3370  1.3524  44994
2009-02-27 15:00:00  1.3370  1.3602  1.2674  1.3292  49206
2009-02-27 16:00:00  1.4993  1.4993  1.4838  1.4993   6700

[116 rows x 5 columns]

Open      object
High      object
Low       object
Close     object
Volume    object
dtype: object

In [69]:
import requests
import pandas as pd

# Construindo a URL
url = 'https://www.alphavantage.co/query?function=MARKET_STATUS&apikey=demo'
r = requests.get(url)
data = r.json()

# Convertendo os dados do JSON para um dataframe
df = pd.DataFrame(data['markets'])

# Exibindo o dataframe
display(df)

,market_type,region,primary_exchanges,local_open,local_close,current_status,notes
0,Equity,United States,"NASDAQ, NYSE, AMEX, BATS",09:30,16:15,closed,
1,Equity,Canada,"Toronto, Toronto Ventures",09:30,16:00,closed,
2,Equity,United Kingdom,London,08:00,16:30,closed,
3,Equity,Germany,"XETRA, Berlin, Frankfurt, Munich, Stuttgart",08:00,20:00,closed,
4,Equity,France,Paris,09:00,17:30,closed,
5,Equity,Spain,"Barcelona, Madrid",09:00,17:30,closed,
6,Equity,Portugal,Lisbon,08:00,16:30,closed,
7,Equity,Japan,Tokyo,09:00,15:00,closed,Noon trading break from 11:30 to 12:30 local time
8,Equity,India,"NSE, BSE",09:15,15:30,closed,
9,Equity,Mainland China,"Shanghai, Shenzhen",09:30,15:00,closed,Noon trading break from 11:30 to 13:00 local time
10,Equity,Hong Kong,Hong Kong,09:30,16:00,closed,Noon trading break from 12:00 to 13:00 local time
11,Equity,Brazil,Sao Paolo,10:00,17:30,closed,
12,Equity,Mexico,Mexico,08:30,15:00,closed,
13,Equity,South Africa,Johannesburg,09:00,17:00,closed,
14,Forex,Global,Global,00:00,23:59,open,"The forex market is open 24 hours a day, EXCEP..."
15,Cryptocurrency,Global,Global,00:00,23:59,open,The cryptocurrency market is open 24 hours a day