In [4]:
!pip install yfinance

Defaulting to user installation because normal site-packages is not writeable
Collecting yfinance
  Downloading yfinance-0.2.63-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.11-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: platformdirs>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.18.1.tar.gz (3.0 MB)
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ------ --------------------------------- 0.5/3.0 MB 3.4 MB/s eta 0:00:01
     ----------------- ---------------------- 1.3/3.0 MB 3.5 MB/s eta 0:00:01
     ------------------------ --------------- 1.8/3.0 MB 3.5 MB/s eta 0:00:01
     ---------------------------------- ----- 2.6/3.0 MB 3.4 MB/s eta 0:00:01
     ---------------------------------------- 3.0/3.0 MB 3.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Collecting curl_cffi>=0.7 (from yfinance)
  Downloading curl_cffi-0.11.3-cp39-abi3-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: protobuf>=3.19.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (4.25.3)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-15.0.1-cp312-cp312-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\programdata\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Downloading yfinance-0.2.63-py2.py3-none-any.whl (118 kB)
Downloading curl_cffi-0.11.3-cp39-abi3-win_amd64.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------- ----------------- 0.8/1.4 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 3.9 MB/s eta 0:00:00
Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Downloading websockets-15.0.1-cp312-cp312-win_amd64.whl (176 kB)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.18.1-py3-none-any.whl size=139097 sha256=3ba704ac20cd6cd8fe78df1177b0e7e3509ba2c6b71a62d1a4ded9d899d24c89
  Stored in directory: c:\users\scitr\appdata\local\pip\cache\wheels\1a\57\6a\bb71346381d0d911cd4ce3026f1fa720da76707e4f01cf27dd
Successfully built peewee
Installing collected packages: peewee, multitasking, websockets, curl_cffi, yfinance
Successfully installed curl_cffi-0.11.3 multitasking-0.0.11 peewee-3.18.1 websockets-15.0.1 yfinance-0.2.63

  WARNING: The script websockets.exe is installed in 'C:\Users\scitr\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script sample.exe is installed in 'C:\Users\scitr\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [5]:
from datetime import date
import pandas as pd
from Alert import Alert 
import yfinance as yf
pd.options.mode.chained_assignment = None  # default='warn'

symbol = "GGAL"
period = "1h"

alert = Alert(symbol,period)

if (period == "1h"):
    df = yf.download(tickers=symbol, period='1d', interval=period)
else:
    df = yf.download(tickers=symbol, period='60d', interval=period)

display(df)
print(len(df))
df.index = df.index.tz_localize(None)
#df.to_excel("GGAL_1H_yf.xlsx")

C:\Users\scitr\AppData\Local\Temp\ipykernel_15500\889071751.py:13: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers=symbol, period='1d', interval=period)
[*********************100%***********************]  1 of 1 completed

Price                          Close       High        Low       Open  Volume
Ticker                          GGAL       GGAL       GGAL       GGAL    GGAL
Datetime
2025-06-23 13:30:00+00:00  51.830002  52.320000  50.660000  51.685001  351493
2025-06-23 14:30:00+00:00  51.610001  52.090000  51.509998  51.830002  174003
2025-06-23 15:30:00+00:00  51.139999  51.564999  51.099998  51.529999  120909
2025-06-23 16:30:00+00:00  50.669998  51.189999  50.430000  51.115002  227319
2025-06-23 17:30:00+00:00  50.250099  50.900002  50.070000  50.669998  204695
2025-06-23 18:30:00+00:00  50.305000  50.593201  50.189999  50.244999  173009
2025-06-23 19:30:00+00:00  50.360001  50.494999  50.200001  50.290001  260186

7

In [15]:
GGAL = yf.Ticker('GGAL')
info = GGAL.fast_info.toJSON()
print (info)

{
    "currency": "USD",
    "dayHigh": 52.31999969482422,
    "dayLow": 50.06999969482422,
    "exchange": "NCM",
    "fiftyDayAverage": 58.75919982910156,
    "lastPrice": 50.369998931884766,
    "lastVolume": 1576003,
    "marketCap": 6674175968.471527,
    "open": 51.685001373291016,
    "previousClose": 52.0,
    "quoteType": "EQUITY",
    "regularMarketPreviousClose": 52.0,
    "shares": 132503000,
    "tenDayAverageVolume": 1945390,
    "threeMonthAverageVolume": 1434563,
    "timezone": "America/New_York",
    "twoHundredDayAverage": 56.833000087738036,
    "yearChange": 0.6149067940349036,
    "yearHigh": 74.0,
    "yearLow": 23.530000686645508
}

In [17]:
GGAL = yf.Ticker('GGAL')
df = GGAL.history(start = '2025-01-01' , end = '2025-06-23')
display(df)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-01-02 00:00:00-05:00,62.223074,68.672298,62.223074,68.473251,1370300,0.0,0.0
2025-01-03 00:00:00-05:00,69.468500,70.652843,67.020176,69.786980,1170800,0.0,0.0
2025-01-06 00:00:00-05:00,72.155676,73.598786,70.523465,70.772278,1453900,0.0,0.0
2025-01-07 00:00:00-05:00,72.046197,73.648552,70.662799,71.877007,1133500,0.0,0.0
2025-01-08 00:00:00-05:00,71.568478,72.673199,69.359020,70.662796,929600,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-13 00:00:00-04:00,55.549999,56.000000,54.080002,54.669998,1772100,0.0,0.0
2025-06-16 00:00:00-04:00,55.080002,55.590000,54.250000,54.500000,1057500,0.0,0.0
2025-06-17 00:00:00-04:00,53.779999,54.970001,52.820000,54.349998,1329000,0.0,0.0
2025-06-18 00:00:00-04:00,54.290001,55.320000,53.689999,54.150002,979700,0.0,0.0
2025-06-20 00:00:00-04:00,54.080002,54.080002,51.930000,52.000000,1124700,0.0,0.0

In [31]:
df = GGAL.history(period = 'max' , interval='1m')
display(df)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-06-16 09:30:00-04:00,55.080002,55.310001,55.080002,55.310001,4232,0.0,0.0
2025-06-16 09:31:00-04:00,55.049999,55.340000,55.049999,55.340000,1073,0.0,0.0
2025-06-16 09:32:00-04:00,55.567001,55.590000,55.310001,55.310001,2182,0.0,0.0
2025-06-16 09:33:00-04:00,55.110001,55.213600,55.080002,55.213600,2093,0.0,0.0
2025-06-16 09:34:00-04:00,55.080002,55.080002,54.299999,54.299999,9446,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-23 15:55:00-04:00,50.439999,50.470001,50.430000,50.430000,15077,0.0,0.0
2025-06-23 15:56:00-04:00,50.439999,50.490002,50.430000,50.474998,14987,0.0,0.0
2025-06-23 15:57:00-04:00,50.474998,50.490002,50.459999,50.480000,10897,0.0,0.0
2025-06-23 15:58:00-04:00,50.480000,50.490002,50.419998,50.439999,21693,0.0,0.0
2025-06-23 15:59:00-04:00,50.430000,50.430000,50.349998,50.360001,36517,0.0,0.0

In [25]:
df_filtrado = df[(df['Dividends'] != 0) | (df['Stock Splits'] != 0)]
display(df_filtrado)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2001-03-27 00:00:00-05:00,11.426243,12.370560,11.284595,12.087265,1701600,0.297,0.0
2004-05-26 00:00:00-04:00,4.087926,4.521033,4.011942,4.103123,505300,0.030,0.0
2011-05-11 00:00:00-04:00,10.272216,10.279842,9.837534,9.929047,243600,0.049,0.0
2012-05-15 00:00:00-04:00,4.090943,4.090943,3.776255,3.891385,245600,0.032,0.0
2014-05-22 00:00:00-04:00,9.745451,9.876314,9.553005,9.830128,190400,0.037,0.0
2015-05-26 00:00:00-04:00,16.415792,16.415792,16.292133,16.338505,321900,0.086,0.0
2016-05-19 00:00:00-04:00,20.791628,20.791628,19.969887,20.310987,421500,0.082,0.0
2017-05-10 00:00:00-04:00,32.644731,32.893512,32.450371,32.691376,313600,0.119,0.0
2018-05-11 00:00:00-04:00,40.700779,41.491464,37.522375,37.569347,1119000,0.362,0.0
2019-05-15 00:00:00-04:00,18.954043,19.810544,18.827154,19.636072,1500200,0.313,0.0
2020-10-09 00:00:00-04:00,5.839495,5.855537,5.598856,5.663026,692500,0.082,0.0
2021-05-14 00:00:00-04:00,6.525644,6.897614,6.525644,6.735888,1340500,0.064,0.0
2022-05-13 00:00:00-04:00,7.418141,7.746526,7.418141,7.637064,713600,0.360,0.0
2022-09-30 00:00:00-04:00,6.348988,6.527953,6.348988,6.357510,560300,0.090,0.0
2023-01-27 00:00:00-05:00,11.730939,11.893750,11.336766,11.345335,415400,0.076,0.0
2023-05-31 00:00:00-04:00,10.344991,10.692198,10.193644,10.567559,576200,0.454,0.0
2023-07-10 00:00:00-04:00,14.671604,14.860510,14.491696,14.509686,409000,0.171,0.0
2023-07-28 00:00:00-04:00,15.270198,15.624475,15.024932,15.188442,760600,0.161,0.0
2023-08-24 00:00:00-04:00,15.229351,15.394289,14.477963,14.532942,755300,0.143,0.0
2023-09-22 00:00:00-04:00,13.832982,14.017668,13.500547,13.519016,449200,0.115,0.0
2024-06-10 00:00:00-04:00,29.207749,31.053037,28.350342,30.810728,796700,0.290,0.0
2024-06-21 00:00:00-04:00,30.278729,31.097588,29.726475,30.526293,1456300,0.700,0.0
2024-07-26 00:00:00-04:00,27.136608,27.974880,27.058629,27.614227,308200,0.657,0.0
2024-08-19 00:00:00-04:00,34.296338,35.500590,33.798712,34.475483,1217100,0.725,0.0
2025-06-03 00:00:00-04:00,56.340000,57.369999,55.400002,56.599998,774200,0.269,0.0

In [ ]:
import yfinance as yf

GGAL = yf.Ticker('GGAL')
df = GGAL.history(start='2025-06-01', end='2025-06-23', interval='5m')
display(df)